# Generated by Django 2.1 on 2018-08-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='Districts',
        ),
    ]
